name: FloodIt
options:
  bundleIdPrefix: com.prashantkulk
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "16.0"
settings:
  base:
    SUPPORTED_PLATFORMS: iphoneos iphonesimulator
    SUPPORTS_MACCATALYST: NO
    TARGETED_DEVICE_FAMILY: "1"
targets:
  FloodIt:
    type: application
    platform: iOS
    sources:
      - FloodIt
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.prashantkulk.floodit
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - sdk: SpriteKit.framework
  FloodItTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - FloodItTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.prashantkulk.floodit.tests
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: FloodIt
