name: FloodIt
options:
  bundleIdPrefix: com.prashantkulk
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "16.0"
settings:
  base:
    SUPPORTED_PLATFORMS: iphoneos iphonesimulator
    SUPPORTS_MACCATALYST: NO
    TARGETED_DEVICE_FAMILY: "1"
targets:
  FloodIt:
    type: application
    platform: iOS
    sources:
      - FloodIt
    info:
      path: FloodIt/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIRequiresFullScreen: true
        UILaunchScreen:
          UIColorName: LaunchBackground
          UIImageName: LaunchLogo
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.prashantkulk.floodit
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - sdk: SpriteKit.framework
  FloodItTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - FloodItTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.prashantkulk.floodit.tests
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: FloodIt
  FloodItUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - FloodItUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.prashantkulk.floodit.uitests
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: FloodIt
